import ThemeProvider from "@/helper/ThemesProvider";
import "@/app/globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import {Comic_Neue, Wendy_One} from 'next/font/google';
export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};


const comic = Comic_Neue({
    subsets: ['latin'],
    weight: ['400', '700'],
});


const wendy = Wendy_One({
    subsets: ["latin"],
    weight: ["400"],
});

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={wendy.className}>
        <ThemeProvider>
            <Header/>
            <main className="bg-transparent grid place-items-start w-screen">
                {children}
            </main>
            <Footer/>
        </ThemeProvider>
        </body>
        </html>
    );
}